---
language: go
install: true # https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
sudo: false

go:
  - 1.15

services: docker

env:
  - distro: ubuntu1604
  - distro: ubuntu1804
  - distro: ubuntu2004
  - distro: debian9
  - distro: debian10

before_install:
  - sudo apt update
  - sudo apt install software-properties-common
  - sudo apt-add-repository --yes ppa:ansible/ansible
  - sudo apt update
  - sudo apt install ansible
  - GO111MODULE=on go get -v github.com/fubarhouse/ansible-role-tester

script:
  - ansible-role-tester full --distribution ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
