---
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Fail when running on non-Debian systems
  fail:
    msg: "Non debian systems are not supported in this role"
  when: ansible_os_family != 'Debian'
